23 as a player i want to use the robber
SE-II-group2/catan-backend pull request #25
Opened 2024-06-13 19:09 UTC by l1wobak

2024-06-13 20:23 UTC, jastornig requested changes

2024-06-13 20:23 UTC, jastornig commented on src/main/java/com/group2/catanbackend/gamelogic/GameLogicController.java
> +    private void makeRollDiceMove(RollDiceDto rollDiceDto, Player player) {
Gibts einen besonderen grund dass das im dice roll drinnen is? Seems bissl out of place auch wenn es damit zusammenhängt. 
Würde das tbh net ins dice roll dto rein tun

2024-06-13 20:23 UTC, jastornig commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        assertTrue(gameLogicController.getBoard().getHexagonList().get(2).isHasRobber());
Seh i grad da aba bitt isHasRobner is ka schöner name. hasRobber bitte

2024-06-13 20:23 UTC, jastornig commented on src/main/java/com/group2/catanbackend/dto/game/RollDiceDto.java
> +        this.moveRobberDto = moveRobberDto;
Pls net ins dice roll. I find das gehört net dahin

2024-06-13 23:38 UTC, nicoszolderits approved these changes

2024-06-14 07:52 UTC, jastornig approved these changes

2024-06-14 12:18 UTC, merged