Feature trading
SE-II-group2/catan-backend pull request #34
Opened 2024-06-26 09:16 UTC by Ghost-Element

2024-06-26 13:52 UTC, l1wobak requested changes, later dismissed
testcases need some work done to be presentable, naming is off and there are a lot of weird lines of code that dont do anything (like setting the eventtype of the DTO which is then never checked again). Also dont write 100 LoC testcases that test 100 different scenarios, split them up

2024-06-26 13:52 UTC, l1wobak commented on src/main/java/com/group2/catanbackend/gamelogic/GameLogicController.java
> +        //optional: notify all users about happened trade
why leave this comment in? this is gonna be the last commit in our project, either do it or delete the comment

2024-06-26 13:52 UTC, l1wobak commented on src/main/java/com/group2/catanbackend/gamelogic/GameLogicController.java
> +        if (isSetupPhase)
replace with method as in other moves

2024-06-26 13:52 UTC, l1wobak commented on src/main/java/com/group2/catanbackend/gamelogic/GameLogicController.java
>          if (activePlayer != player)
replace with method as in other moves

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        MakeTradeOfferMoveDto makeTradeOfferMoveDto = new MakeTradeOfferMoveDto(negate(offeredResources), wantedResources, sendToPlayer);
why negate the array instead of just initializing it with negative values?

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        gameLogicController.setSetupPhase(false);
its better to put the premise to the top of the method

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        gameLogicController.makeMove(new MakeTradeOfferMoveDto(negate(offeredResources), wantedResources, sendToPlayer), player1);
again, why negate instead of just initialsizing arrays with negative values?

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        tradeOfferDto.setEventType(null);
Why set the eventType to null?

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +    void testMakeTradingWithPlayer(){
unclear name, it should better represent what the test does.

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +    void testTradingOverDiceRoll(){
again unclear name, should be something like "tradePersistsOverDiceBeingRolled" or something

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        gameLogicController.makeMove(new MakeTradeOfferMoveDto(negate(offeredResources), wantedResources, sendToPlayer), player1);
remove negate

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        TradeOfferDto tradeOfferDto = new TradeOfferDto(negate(wantedResources), offeredResources, player1.toInGamePlayerDto());
remove negate

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        tradeOfferDto.setEventType(null);
why set the eventtype to null?

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        gameLogicController.makeMove(new MakeTradeOfferMoveDto(negate(offeredResources), wantedResources, sendToPlayer), player1);
remove negate

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerExpandedTest.java
> +        Exception exception = assertThrows(InvalidGameMoveException.class, () -> gameLogicController.makeMove(new AcceptTradeOfferMoveDto(tradeOfferDto), player2));
should be 2 testcases, one to check if multiple trades overwrite each other and one to check if the second can then be accepted

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        player2.adjustResources(wantedResources);
why adjust the resources if they dont accept the trade in this test

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testMakeTradeOfferMoveWithPlayerWorking(){
unclear name, should just be testMakeTradeOfferMoveGetsSentCorrectly

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testMakeTradeOfferMoveWithBankWorking(){
unclear name, should say that it gets sent correctly

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        verify(messagingService, times(2)).notifyGameProgress(anyString(), any(CurrentGameStateDto.class));
why is it sent twice here?

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testMakeTradeOfferMoveGeneralFailing(){
split into multiple testcases

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        exception = assertThrows(NotActivePlayerException.class, () ->gameLogicController.makeMove(new MakeTradeOfferMoveDto(negate(offeredResources), wantedResources, sendToPlayer), player2));
split into own test

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testMakeTradeOfferMoveWithBankFailing() {
unclear name, why does it fail? and should say throwsExceptionWhen instead of just failing

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testAcceptTradeOfferMoveFailing(){
split into many testcases

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        gameLogicController.setSetupPhase(true);//technically could never happen
if it coult never happen then dont test it

2024-06-26 13:52 UTC, l1wobak commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        tradeOfferDto1.setEventType(null);
why always set the event type to null???

2024-06-26 21:50 UTC, jastornig commented
Hello @Ghost-Element, congratulations, your pull request has been reopened. Fix the issues stated by @l1wobak and we are good to go. If you think that Lukas is not right in one of his comments, be so kind and explain why things are like they are. Regards.

2024-06-27 21:30 UTC, Ghost-Element commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +    void testAcceptTradeOfferMoveFailing(){
split it and named them properly

2024-06-27 21:31 UTC, Ghost-Element commented on src/test/java/com/group2/catanbackend/gamelogic/GameLogicControllerSimpleTest.java
> +        gameLogicController.setSetupPhase(true);//technically could never happen
deleted the test and the check because it can never happen (without other bucks)

2024-06-27 23:42 UTC, jastornig approved these changes
I will let the rather non Informational Test names pass

2024-06-27 23:44 UTC, merged